[Default]
rels = 'application/vnd.openxmlformats-package.relationships+xml'
xml = 'application/xml'
png = 'image/png'
jpeg = 'image/jpeg'
jpg = 'image/jpeg'
tiff = 'image/tiff'
gif = 'image/gif'

[Override]
'/xl/workbook.xml' = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml'
'/docProps/core.xml' = 'application/vnd.openxmlformats-package.core-properties+xml'
'/docProps/app.xml' = 'application/vnd.openxmlformats-officedocument.extended-properties+xml'
'/xl/styles.xml' = 'application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml'
'/xl/sharedStrings.xml' = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml'
'/xl/worksheets/sheet1.xml' = 'application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml'
'/xl/theme/theme1.xml' = 'application/vnd.openxmlformats-officedocument.theme+xml'
'/xl/drawings/drawing1.xml' = 'application/vnd.openxmlformats-officedocument.drawing+xml'
'/_rels/.rels' = 'application/vnd.openxmlformats-package.relationships+xml'
'/xl/_rels/workbook.xml.rels' = 'application/vnd.openxmlformats-package.relationships+xml'
'/xl/worksheets/_rels/sheet1.xml.rels' = 'application/vnd.openxmlformats-package.relationships+xml'
'/xl/drawings/_rels/drawing1.xml.rels' = 'application/vnd.openxmlformats-package.relationships+xml'
